### ISSUE TITLE
Version of qiskit

### ISSUE THREAD

**Issue by raywu0123** [milesgep/Quantum-Reinforcement-Learning#1]
I got this error while running your program `quantumGridWorld`
```
Traceback (most recent call last):
  File "quantumGridWorld.py", line 237, in <module>
    Q, stats, memory = q_learning(env, 500)
  File "quantumGridWorld.py", line 206, in q_learning
    action = collapseActionSelectionMethod(Q_program, eigenAction, qr, cr)
  File "quantumGridWorld.py", line 129, in collapseActionSelectionMethod
    classical_state = result['classical_state']
KeyError: 'classical_state'
```

I think its a problem with qiskit 's version. Would you be so kind to tell me which version you are using ?

**Comment by erdisayar** [comment]
I think they are the versions
`pip install qiskit==0.5.7`
`pip install networkx==2.3`
